#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorNone)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorNone)
#pragma config(Sensor, dgtl5,  extensionEncoder, sensorNone)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorNone)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorNone)
#pragma config(Sensor, dgtl11, armEncoder,     sensorNone)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armRightEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  armLeftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intake1,       tmotorVex269, openLoop)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex269, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port5,           frontLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port6,           ArmRight,      tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port7,           ArmLeft,       tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port8,           ArmRightTop,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           ArmLeftTop,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          intake2,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
This program is designed to give new programmers beginning code that allows their robots to move from
point to point on the gameboard. The program uses three functions: moveForward, turnRight, and turnLeft
to move around the gameboard.  Each of the functions accepts two paramenters: encoderCounts and speed.
----------------------------------------------------------------------------------------------------*/

//Function to move the robot forward for a specified amount of encoder counts
//at a specified speed
void moveForward(int encoderCounts, int speed)
{
	//Clear the encoders before using them
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	//While both of the encoders are less than the specified amount
	while(SensorValue[rightEncoder] < encoderCounts)
	{
		//If the two encoder values are equal
		if(abs(SensorValue[rightEncoder]) == abs(SensorValue[leftEncoder]))
		{
			//Move the robot forward at the specified speed
			motor[rearRightMotor] = speed;
			motor[frontRightMotor] = speed;
			motor[rearLeftMotor] = speed;
			motor[frontLeftMotor] = speed;
		}

		//If the right encoder is greater than the left encoder (veering to the left)
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]))
		{
			//Adjust the robot slightly to the right
			motor[rearRightMotor] = speed;
			motor[frontRightMotor] = speed;
			motor[rearLeftMotor] = speed + 10;
			motor[frontLeftMotor] = speed + 10;
		}

		//If the left encoder is greater than the right encoder (veering to the right)
		else if(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder]))
		{
			//Adjust the robot slightly to the right
			motor[rearRightMotor] = speed + 10;
			motor[frontRightMotor] = speed + 10;
			motor[rearLeftMotor] = speed;
			motor[frontLeftMotor] = speed;
		}
	}

	//Stop the robot
	motor[rearRightMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
}

//Turn the robot left for the specified encoder counts
//at a specified speed
void turnLeft(int encoderCounts, int speed)
{
	//Clear the encoders before using them
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	//While the absolute value of the right motor's encoder is less
	//than the specified amount
	while(abs(SensorValue[rightEncoder]) < encoderCounts)
	{
		//Turn the robot to the left at the specified speed
		motor[rearRightMotor] = speed;
		motor[frontRightMotor] = speed;
		motor[rearLeftMotor] = -speed;
		motor[frontLeftMotor] = -speed;
	}

	//Stop the robot
	motor[rearRightMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
}

//Turn the robot left for the specified encoder counts
//at a specified speed
void turnRight(int encoderCounts, int speed)
{
	//Clear the encoders
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	//While the absolute value of the left motor's encoder is less
	//than the specified amount
	while(abs(SensorValue[leftEncoder]) < encoderCounts)
	{
		//Turn the robot to the right at the specified speed
		motor[rearRightMotor] = -speed;
		motor[frontRightMotor] = -speed;
		motor[rearLeftMotor] = speed;
		motor[frontLeftMotor] = speed;
	}

	//Stop the robot
	motor[rearRightMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
}

void raiseUpBottom(int encoderCounts, int speed)
{
	motor[armRight] = speed;
	motor[armLeft] = speed;

	/*
	SensorValue[armRightEncoder] = 0;
	SensorValue[armLeftEncoder]  = 0;

	while(abs(SensorValue[leftEncoder]) < encoderCounts)
	{

		//If the two encoder values are equal
		if(abs(SensorValue[armRightEncoder]) == abs(SensorValue[armLeftEncoder]))
		{
			//Move the robot forward at the specified speed
			motor[armRight] = speed;
			motor[armLeft] = speed;

		}

		//If the right encoder is greater than the left encoder (veering to the left)
		else if(abs(SensorValue[armRightEncoder]) > abs(SensorValue[armLeftEncoder]))
		{
			//Adjust the robot slightly to the right
			motor[armRight] = speed;
			motor[armLeft] = speed + 5;
		}

		//If the left encoder is greater than the right encoder (veering to the right)
		else if(abs(SensorValue[armRightEncoder]) < abs(SensorValue[armLeftEncoder]))
		{
			//Adjust the robot slightly to the right
			motor[armRight] = speed + 5;
			motor[armLeft] = speed;
		}

	}
	*/
}

void raiseUpIntake(int encoderCounts, int speed)
{
	motor[intake1] = -speed;
	motor[intake2] = -speed;
}

task main()
{
	//Move the robot forward for 1000 encoder counts
	//at a speed of 50, then wait for half of a second
	moveForward(100, 50);
	wait1Msec(100);

	//Turn the robot to the right for 480 encoder counts
	//at a speed of 25, then wait for half of a second
	turnRight(100, 25);
	wait1Msec(100);

	//Turn the robot to the left for 480 encoder counts
	//at a speed of 25, then wait for half of a second
	turnLeft(100, 25);
	wait1Msec(100);

	raiseUpBottom (5, 5);
	wait1Msec(100);

	raiseUpIntake (5, 5);
	wait1Msec(100);

}
