#pragma config(Motor,  port2,           FRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           RRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           FLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RLeft,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int thresh = 25;
	while(1)
	{
		if(abs(vexRT[Ch3])>thresh)
				{
						motor[FLeft] = vexRT[Ch3];
						motor[RLeft] =  vexRT[Ch3];
				}
				else if(abs(vexRT[Ch3])<=thresh)
				{
						motor[FLeft] = 0;
						motor[RLeft] =  0;
				}
				if(abs(vexRT[Ch2])>thresh)
				{
						motor[FRight] = vexRT[Ch2];
						motor[RRight] =  vexRT[Ch2];
				}
				else if(abs(vexRT[Ch2])<=thresh)
				{
						motor[FRight] = 0;
						motor[RRight] =  0;
				}
	}
}
