#pragma config(Sensor, dgtl1,  Rightlim,       sensorTouch)
#pragma config(Sensor, dgtl2,  Leftlim,        sensorTouch)
#pragma config(Sensor, dgtl3,  Toplim,         sensorTouch)
#pragma config(Motor,  port1,           rotate,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           RearRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           RearLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           ArmRight,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           ArmLeft,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           ArmRightTop,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           ArmLeftTop,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FrontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           FrontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          claw,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		int thresh = 25;
		int thresh2 = 50;
		while(1)
		{
			if(abs(vexRT[Ch3])>thresh)
				{
						motor[frontLeft] = vexRT[Ch3];
						motor[rearLeft] =  vexRT[Ch3];
				}
				else if(abs(vexRT[Ch3])<=thresh)
				{
						motor[frontLeft] = 0;
						motor[rearLeft] =  0;
				}
				if(abs(vexRT[Ch2])>thresh)
				{
						motor[frontRight] = vexRT[Ch2];
						motor[rearRight] =  vexRT[Ch2];
				}
				else if(abs(vexRT[Ch2])<=thresh)
				{
						motor[frontRight] = 0;
						motor[rearRight] =  0;
				}



		if((vexRT [Ch2Xmtr2]) > thresh && !SensorValue[Rightlim] && !SensorValue[Leftlim])
				{
						motor[ArmRight] = vexRT[Ch2Xmtr2];
						motor[ArmLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT [Ch2Xmtr2]) > thresh && !SensorValue[Rightlim] && SensorValue[Leftlim])
				{
						motor[ArmRight] = vexRT[Ch2Xmtr2];
						motor[ArmLeft] = 0;
				}
				else if((vexRT [Ch2Xmtr2]) > thresh && SensorValue[Rightlim] && !SensorValue[Leftlim])
				{
						motor[ArmRight] = 0;
						motor[ArmLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT [Ch2Xmtr2]) < -thresh)
				{
							motor[ArmRight] = vexRT[Ch2Xmtr2];
							motor[ArmLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT[Ch2Xmtr2]) <=thresh||(SensorValue[Rightlim]&&SensorValue[Leftlim]))
				{
						motor[ArmRight] = 0;
						motor[ArmLeft] = 0;
				}
				if(vexRT [Ch3Xmtr2] > thresh&&SensorValue[Toplim]==0)
				{
						motor[ArmRightTop] = vexRT[Ch3Xmtr2];
						motor[ArmLeftTop] = vexRT[Ch3Xmtr2];
				}
				else if(vexRT[Ch3Xmtr2] < -thresh)
				{
						motor[ArmRightTop] = vexRT[Ch3Xmtr2];
						motor[ArmLeftTop] = vexRT[Ch3Xmtr2];
				}
				else if(abs(vexRT[Ch3Xmtr2]) <=thresh||SensorValue[Toplim]==1)
				{
						motor[ArmRightTop] = 0;
						motor[ArmLeftTop] = 0;
				}
				if(vexRT[Btn5U])
				{
						motor[rotate] = 100;

				}
				else if(vexRT[Btn5D])
				{
						motor[rotate] = -100;
				}
				else
				{
						motor[rotate] = 0;
				}
				if(vexRT[Btn6U])
				{
						motor[claw] = 70;

				}
				else if(vexRT[Btn6D])
				{
						motor[claw] = -70;
				}
				else
				{
						motor[claw] = 0;
				}

				wait1Msec(30);

		}


}
