#pragma config(Motor,  port2,           RearRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           RearLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           FrontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		int thresh = 25;
		while(1)
		{
			if(abs(vexRT[Ch3]) > thresh)
				 motor[RearRight] = vexRT[Ch3];
			else motor[RearRight] = 0;
			if(abs(vexRT[Ch2]) > thresh)
				motor[RearLeft] = vexRT[Ch2];
			else motor[RearLeft] = 0;
				if(abs(vexRT[Ch3Xmtr2]) > thresh)
				 motor[FrontRight] = vexRT[Ch3Xmtr2];
			else motor[FrontRight] = 0;
			if(abs(vexRT[Ch2Xmtr2]) > thresh)
				motor[FrontLeft] = vexRT[Ch2Xmtr2];
			else motor[FrontLeft] = 0;




		}


}
