#pragma config(Motor,  port1,           rotate,        tmotorVex269, openLoop)
#pragma config(Motor,  port10,          claw,          tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		if(vexRT(Btn5U))
		{
			motor[rotate] = 80;
		}
		else if(vexRT(Btn5D))
		{
			motor[rotate] = -80;
		}
		else
		{
			motor[rotate] = 0;
		}
		if(vexRT(Btn6U))
		{
			motor[claw] = 80;
		}
		else if(vexRT(Btn6D))
		{
			motor[claw] = -80;
		}
		else
		{
			motor[claw] = 0;
		}
		wait1Msec(30);


	}
}
