#pragma config(Motor,  port1,           IntakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           FRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           RRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           TRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           TLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           BLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           RLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          IntakeRight,   tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int thresh = 25;
	while(1)
	{
				if(abs(vexRT[Ch3])>thresh)
				{
						motor[FLeft] = vexRT[Ch3];
						motor[RLeft] =  vexRT[Ch3];
				}
				else if(abs(vexRT[Ch3])<=thresh)
				{
						motor[FLeft] = 0;
						motor[RLeft] =  0;
				}
				if(abs(vexRT[Ch2])>thresh)
				{
						motor[FRight] = vexRT[Ch2];
						motor[RRight] =  vexRT[Ch2];
				}
				else if(abs(vexRT[Ch2])<=thresh)
				{
						motor[FRight] = 0;
						motor[RRight] =  0;
				}

				if(abs(vexRT[Ch3Xmtr2])>thresh)
				{
						motor[TLeft] = - vexRT[Ch3Xmtr2];
						motor[BLeft] =  - vexRT[Ch3Xmtr2];
						motor[TRight] = - vexRT[Ch2Xmtr2];
						motor[BRight] =  - vexRT[Ch2Xmtr2];
				}
				else if(abs(vexRT[Ch3Xmtr2])<=thresh)
				{
						motor[TLeft] = 0;
						motor[BLeft] = 0;
						motor[TRight] = 0;
						motor[BRight] = 0;
				}
				if(abs(vexRT[Ch2Xmtr2])>thresh)
				{
						motor[IntakeLeft] = 100;
						motor[IntakeRight] = 100;
				}
				else if(abs(vexRT[Ch2Xmtr2])<=thresh)
				{
						motor[IntakeLeft] = 0;
						motor[IntakeRight] = 0;
				}
		}
}
