#pragma config(Motor,  port2,           serv,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
	if(vexRT(Btn5D))
	{
		motor[serv] = -127;
	}
	else if(vexRT(Btn5U))
	{
		motor[serv] = 127;
	}
	wait1Msec(30);
}



}
