#pragma config(Sensor, dgtl1,  Rightlim,       sensorTouch)
#pragma config(Sensor, dgtl2,  Leftlim,        sensorTouch)
#pragma config(Sensor, dgtl3,  Toplim,         sensorTouch)
#pragma config(Motor,  port1,           Intake1,       tmotorVex269, openLoop)
#pragma config(Motor,  port2,           RRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           FRight,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           RLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           FLeft,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           ArmRight,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           ArmLeft,       tmotorVex393, openLoop)
#pragma config(Motor,  port8,           ArmRight2,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           ArmLeft2,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          Intake2,       tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		int thresh = 25;
		while(1==1)
		{
				if(abs(vexRT[Ch3])>thresh)
				{
						motor[FLeft] = vexRT[Ch3];
						motor[RLeft] =  vexRT[Ch3];
				}
				else if(abs(vexRT[Ch3])<=thresh)
				{
						motor[FLeft] = 0;
						motor[RLeft] =  0;
				}
				if(abs(vexRT[Ch2])>thresh)
				{
						motor[FRight] = vexRT[Ch2];
						motor[RRight] =  vexRT[Ch2];
				}
				else if(abs(vexRT[Ch2])<=thresh)
				{
						motor[FRight] = 0;
						motor[RRight] =  0;
				}
				if((vexRT [Ch2Xmtr2]) > thresh && !SensorValue[Rightlim] && !SensorValue[Leftlim])
				{
						motor[ArmRight] = vexRT[Ch2Xmtr2];
						motor[ArmLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT [Ch2Xmtr2]) > thresh && !SensorValue[Rightlim] && SensorValue[Leftlim])
				{
						motor[ArmRight] = vexRT[Ch2Xmtr2];
						motor[ArmLeft] = 0;
				}
				else if((vexRT [Ch2Xmtr2]) > thresh && SensorValue[Rightlim] && !SensorValue[Leftlim])
				{
						motor[ArmRight] = 0;
						motor[ArmLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT [Ch2Xmtr2]) < -thresh)
				{
							motor[ArmRight] = vexRT[Ch2Xmtr2];
							motor[ArmLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT[Ch2Xmtr2]) <=thresh||(SensorValue[Rightlim]&&SensorValue[Leftlim]))
				{
						motor[ArmRight] = 0;
						motor[ArmLeft] = 0;
				}
				if(vexRT [Ch3Xmtr2] > thresh&&SensorValue[Toplim]==0)
				{
						motor[ArmRight2] = vexRT[Ch3Xmtr2];
						motor[ArmLeft2] = vexRT[Ch3Xmtr2];
				}
				else if(vexRT[Ch3Xmtr2] < -thresh)
				{
						motor[ArmRight2] = vexRT[Ch3Xmtr2];
						motor[ArmLeft2] = vexRT[Ch3Xmtr2];
				}
				else if(abs(vexRT[Ch3Xmtr2]) <=thresh||SensorValue[Toplim]==1)
				{
						motor[ArmRight2] = 0;
						motor[ArmLeft2] = 0;
				}
				if(vexRT[Btn5UXmtr2])
				{
						motor[Intake1] = 100;
						motor[Intake2] = 100;
				}
				else if(vexRT[Btn5DXmtr2])
				{
						motor[Intake1] = -100;
						motor[Intake2] = -100;
				}
				else
				{
						motor[Intake1] = 0;
						motor[Intake2] = 0;
				}
		}
}
