#pragma config(Sensor, dgtl1,  Rightlim,       sensorTouch)
#pragma config(Sensor, dgtl2,  Leftlim,        sensorTouch)
#pragma config(Sensor, dgtl3,  Toplim,         sensorTouch)
#pragma config(Motor,  port1,           intake1,       tmotorVex269, openLoop)
#pragma config(Motor,  port2,           rearRightMotor,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           frontRightMotor,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rearLeftMotor,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           frontLeftMotor,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armRight,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armLeft,       tmotorVex393, openLoop)
#pragma config(Motor,  port8,           armRightTop,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           armLeftTop,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intake2,       tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		int thresh = 25;
		while(1==1)
		{
				if(abs(vexRT[Ch3])>thresh)
				{
						motor[frontLeftMotor] = vexRT[Ch3];
						motor[rearLeftMotor] =  vexRT[Ch3];
				}
				else if(abs(vexRT[Ch3])<=thresh)
				{
						motor[frontLeftMotor] = 0;
						motor[rearLeftMotor] =  0;
				}
				if(abs(vexRT[Ch2])>thresh)
				{
						motor[frontRightMotor] = vexRT[Ch2];
						motor[rearRightMotor] =  vexRT[Ch2];
				}
				else if(abs(vexRT[Ch2])<=thresh)
				{
						motor[frontRightMotor] = 0;
						motor[rearRightMotor] =  0;
				}
				if((vexRT [Ch2Xmtr2]) > thresh && !SensorValue[Rightlim] && !SensorValue[Leftlim])
				{
						motor[armRight] = vexRT[Ch2Xmtr2];
						motor[armLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT [Ch2Xmtr2]) > thresh && !SensorValue[Rightlim] && SensorValue[Leftlim])
				{
						motor[armRight] = vexRT[Ch2Xmtr2];
						motor[armLeft] = 0;
				}
				else if((vexRT [Ch2Xmtr2]) > thresh && SensorValue[Rightlim] && !SensorValue[Leftlim])
				{
						motor[armRight] = 0;
						motor[armLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT [Ch2Xmtr2]) < -thresh)
				{
							motor[armRight] = vexRT[Ch2Xmtr2];
							motor[armLeft] = vexRT[Ch2Xmtr2];
				}
				else if((vexRT[Ch2Xmtr2]) <=thresh||(SensorValue[Rightlim]&&SensorValue[Leftlim]))
				{
						motor[armRight] = 0;
						motor[armLeft] = 0;
				}
				if(vexRT [Ch3Xmtr2] > thresh&&SensorValue[Toplim]==0)
				{
						motor[armRightTop] = vexRT[Ch3Xmtr2];
						motor[armLeftTop] = vexRT[Ch3Xmtr2];
				}
				else if(vexRT[Ch3Xmtr2] < -thresh)
				{
						motor[armRightTop] = vexRT[Ch3Xmtr2];
						motor[armLeftTop] = vexRT[Ch3Xmtr2];
				}
				else if(abs(vexRT[Ch3Xmtr2]) <=thresh||SensorValue[Toplim]==1)
				{
						motor[armRightTop] = 0;
						motor[armLeftTop] = 0;
				}
				if(vexRT[Btn5UXmtr2])
				{
						motor[intake1] = 100;
						motor[intake2] = 100;
				}
				else if(vexRT[Btn5DXmtr2])
				{
						motor[intake1] = -100;
						motor[intake2] = -100;
				}
				else
				{
						motor[intake1] = 0;
						motor[intake2] = 0;
				}
		}
}
